# Root task runner.
#
# FROZEN — do not edit this file (CLAUDE.md §14.2). It exists only to import
# the two per-track task files so that Lakshay and Shaurya never edit the same
# justfile and never conflict.
#
#   Track A (infra) -> just/infra.just
#   Track B (AI)    -> just/ai.just

set dotenv-load := true
set shell := ["bash", "-uc"]

import 'just/infra.just'
import 'just/ai.just'

# List every available task.
default:
    @just --list --unsorted
